"""test changes

Revision ID: 4e5d7dd785fb
Revises: 68a5ea7bf7cd
Create Date: 2026-01-02 19:09:39.576577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e5d7dd785fb'
down_revision: Union[str, Sequence[str], None] = '68a5ea7bf7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('fake', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'fake')
    # ### end Alembic commands ###
